### PR TITLE
Fix all remaining negative zero bugs

### LINKED ISSUE #100: TurboWarp breaks any operations that depend on negitive 0 and the value not being NaN
A simple example is ( ( 1 / 0 ) / ( -0 + -0 ) ) which returns -Infinity in TurboWarp but Infinity in Scratch
image

See demo project 773175910 on [Scratch](https://scratch.mit.edu/projects/773175910/) and [TurboWarp](https://turbowarp.org/773175910).

This happens because ( 1 / 0 ) = Infinity and ( -0 + -0) = -0. If you double click the ( -0 + -0) block in Scratch it will report 0, but internally it is still -0, it looks like 0 because `(-0).toString()` is 0. ( Infinity / -0 ) = -Infinity, so Scratch handles the block correctly.

TurboWarp on the other hand turns the -0 into a 0 leaving ( Infinity / 0 ) = Infinity. This happens because TurboWarp tries to deal with the potential NaN using `|| 0`. This operation inadvertently also converts -0 into 0, as `(-0) || 0 === 0`.

### LINKED ISSUE #224: -#/0 Returns positive Infinity with compiler off.
The output should return negative Infinity, but it returns positive Infinity, I'm unable to replicate the bug in another project in Turbowarp or vanilla scratch, I've tested this on Ubuntu Desktop & Firefox running Turbowarp.

image
image

### PR DESCRIPTION
**Pull request by GarboMuffin**
My understanding is that the new compiler tries to reason about -0 a good bit but the use of `(x||0)` prevents it from fixing all of the bugs. This replaces that syntax with a jsexecute function that returns 0 only for NaN and leaves -0 unchanged.

Draft because:
 * Need more performance testing. Brief initial testing found no slowdown in Linux in Scratch. @Geotale said this might even be faster in ideal conditions.
 * Need some solid test cases to add.

Test @ https://experiments.turbowarp.org/fix-negative-zero/

### CODE REVIEW

**Comment by Tacodiva** [comment]
How does this effect performance?

**Comment by GarboMuffin** [comment]
My only datapoint so far is that `isNaN(value) ? 0 : value` made Linux in Scratch run 50% slower in Firefox whereas `value === value ? value : 0` made it have no measurable difference compared to develop. Maybe next weekend or so I can look around a bit more. I'm particularly worried about performance of generator functions in Firefox which don't get into the highest tier of JIT so probably no inlining at all in that case.

**Comment by GarboMuffin** [comment]
some years ago i thought about gathering up some hundreds of projects so i can make a proper performance tracking and comparison system, though i never got around to that. would've been really cool to have these last weeks

**Comment by GarboMuffin** [comment]
it's also on https://experiments.turbowarp.org/fix-negative-zero/ if you were interested in testing anything yourself

Linux in Scratch, in Firefox, with warp timer, goes from around 36s -> around 40s to boot so it's measurable though less catastrophic than I expected. Chrome in the same configuration is maybe just a tiny bit slower but I think it's within noise.

File: src/compiler/jsgen.js [hunk 1]
```diff
@@ -185,9 +185,9 @@ class JSGenerator {
                 return `(+${this.descendInput(node.target.toType(InputType.BOOLEAN))})`;
             }
             if (node.target.isAlwaysType(InputType.NUMBER_OR_NAN)) {
-                return `(${this.descendInput(node.target)} || 0)`;
+                return `toNotNaN(${this.descendInput(node.target)})`;
```
Comment (Tacodiva) [inline src/compiler/jsgen.js:188]: Could add a check to see if the node can be negative zero, and if it can't, maybe use the old `|| 0` method if it's faster. Doubt it'll make a huge difference tho

Comment (GarboMuffin) [reply src/compiler/jsgen.js:188]: I think I tried this and it only affected like 3 places in the entire test suite, most of those being in the generate comparison testing matrix which isn't very real-world. Think Linux in Scratch had no changes in generated code at all. Don't think it's worth checking that at this time

**Comment by Geotale** [comment]
I'm a tiny bit sad to see even any performance deficit on any browser (of course it would be Firefox tbh), but I'm extremely happy it's minor enough (and prooobably only in Firefox maybe? Idk I'd have to ask my friend who knows way too much about Chromium) this may be merged <3

**Comment by GarboMuffin** [comment]
the justification is

 - firefox is used by like 1% of users (this applies to the internet broadly, but especially to us due to high usage of chromebooks in education environments)
 - the performance loss is only when the function is compiled as a generator function, in which case Firefox is already 3-4x slower than the competition so this doesn't move that needle much
 - most important parts of projects are compiled to regular functions, not generators, unless you enable warp timer in which case you are making a performance tradeoff anyways, so again this isn't moving the needle much
